### PR TITLE
Refactoring: Regression Tests

### PR DESCRIPTION
**Pull request by ssvlab**
- Updated regression folder for CBMC and ESBMC model checkers
- Added Synthesized Controllers in Closed-Loop and State-Space for CBMC and ESBMC model checkers
- Added script to run all regression tests
- Updated TravisCI script to execute ESBMC and CBMC test cases
- Added CPPLint Checker into TravisCI Script
- Added Scripts to perform CPPLint Checker.
- Added Support for ESBMC 4.4.1 and CBMC 5.7

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]
Looks good to me.

**Comment by ssvlab** [comment]
@lennonchaves why there are so many failed travis tasks? Could you fix them before we merge?

**Comment by feliperodri** [comment]
@lennonchaves why there are so many failed travis tasks? Could you fix them before we merge?

**Comment by lennonchaves** [comment]
I'm working to fix it. The TravisCI is failing due to many test cases to run in CBMC and ESBMC. @feliperodri

**Comment by lennonchaves** [comment]
@feliperodri The TravisCI is fixed.

**Pull request merged**
