### PR TITLE
Refactored dsverifier.cpp #114

### PR DESCRIPTION
**Pull request by lennonchaves**

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]
Looks good to me. However, next time let's make small PRs to make our review process easier.

**Comment by lennonchaves** [comment]
@feliperodri please, get the updates on master branch, and then the build on travisCI will be okay.

And please, push the remaining code to finish your refactoring.
Thanks,

Lennon.

**Comment by lennonchaves** [comment]
And please, run the regression test in **your machine** just to check if the test cases are okay.
Thanks,
Lennon.

**Review by ssvlab — CHANGES_REQUESTED** [review]
Please, see the comments before merging

**Comment by lennonchaves** [comment]
@feliperodri where is the dsverifier toolbox? It was deleted in your branch.

**Comment by lennonchaves** [comment]
@feliperodri any updates? I'm still waiting for your code. I tried to fix the TravisCI, however you need to commit your changes.

**Pull request closed without merging**
